name: "${pom.artifactId}"
main: hmmhmmmm.worldprotect.WorldProtect
author: "HmmHmmmm, Dinaster85"
version: "${pom.version}"
api: ["1.0.9"]
website: https://github.com/Dinaster85/WorldProtect

permissions:
  worldprotect:
    default: false
    children:
      worldprotect.command:
        default: op